### ISSUE TITLE
Error coming from event-manager in non browser environment.

### ISSUE THREAD

**Issue by gsf-smclamb** [uber/react-map-gl#347]
We have some tests that render react-map-gl components using Jest and noticed an error after upgrading to v3:
TypeError: this.manager.get is not a function

It looks like the event-manager was updated to access more methods on the manager but the mock manager wasn't updated.  I fixed the problem locally by adding the chainedNoop functions for instance.get and instance.set though that may not be the best fix.  If it is, I'm happy to submit a PR for with the changes.  Thanks!

**Comment by ibgreen** [comment]
@gsf-smclamb A PR sounds good, your proposal seems inline with what was intended. 

@ericsoco assume you have no objections.

**Comment by ericsoco** [comment]
Certainly. I think @Pessimistress may have added the methods in question -- regardless, please cc us both on the PR. Thanks @gsf-smclamb!
