### PR TITLE
Add missing methods to mock manager.

### LINKED ISSUE #347: Error coming from event-manager in non browser environment.
We have some tests that render react-map-gl components using Jest and noticed an error after upgrading to v3:
TypeError: this.manager.get is not a function

It looks like the event-manager was updated to access more methods on the manager but the mock manager wasn't updated.  I fixed the problem locally by adding the chainedNoop functions for instance.get and instance.set though that may not be the best fix.  If it is, I'm happy to submit a PR for with the changes.  Thanks!

### PR DESCRIPTION
**Pull request by gsf-smclamb**
Added missing methods to mock manager to prevent errors in non browser environments.

This fixes #347 .
@ibgreen @ericsoco

### CODE REVIEW

**Comment by ibgreen** [comment]
@gsf-smclamb - will land as soon as you sign the CLA.

File: src/utils/event-manager/event-manager.js [hunk 1]
```diff
@@ -16,6 +16,8 @@ function ManagerMock(m) {
   instance.off = chainedNoop;
   instance.destroy = chainedNoop;
   instance.emit = chainedNoop;
+  instance.get = chainedNoop;
```
Comment (ericsoco) [inline src/utils/event-manager/event-manager.js]: This mock is incorrect -- `get()` should return a value, not the instance.
See also [deck.gl](https://github.com/uber/deck.gl/blob/master/src/controls/events/event-manager.js#L16)...is it time to break off `event-manager` into a module/package shared between these libs? /cc @ibgreen @Pessimistress

**Comment by pelotom** [comment]
We're awaiting this fix with much anticipation, any timeline for a new release?
